module.exports = {
  "enforce-store-naming-convention": require("./enforce-store-naming-convention/enforce-store-naming-convention"),
  "enforce-effect-naming-convention": require("./enforce-effect-naming-convention/enforce-effect-naming-convention"),
  "no-getState": require("./no-getState/no-getState"),
  "no-unnecessary-duplication": require("./no-unnecessary-duplication/no-unnecessary-duplication"),
  "prefer-sample-over-forward-with-mapping": require("./prefer-sample-over-forward-with-mapping/prefer-sample-over-forward-with-mapping"),
  "no-useless-methods": require("./no-useless-methods/no-useless-methods"),
  "no-ambiguity-target": require("./no-ambiguity-target/no-ambiguity-target"),
  "no-watch": require("./no-watch/no-watch"),
  "no-unnecessary-combination": require("./no-unnecessary-combination/no-unnecessary-combination"),
  "no-duplicate-on": require("./no-duplicate-on/no-duplicate-on"),
  "strict-effect-handlers": require("./strict-effect-handlers/strict-effect-handlers"),
  "enforce-gate-naming-convention": require("./enforce-gate-naming-convention/enforce-gate-naming-convention"),
  "keep-options-order": require("./keep-options-order/keep-options-order"),
  "no-forward": require("./no-forward/no-forward"),
  "no-guard": require("./no-guard/no-guard"),
  "mandatory-scope-binding": require("./mandatory-scope-binding/mandatory-scope-binding"),
  "prefer-useUnit": require("./prefer-useUnit/prefer-useUnit"),
  "no-patronum-debug": require("./no-patronum-debug/no-patronum-debug"),
};
