name: review

on:
  pull_request:
    branches: [master]

  reports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install
      - run: yarn test --coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
